### ISSUE TITLE
Unexpected response code 403

### ISSUE THREAD

**Issue by voluphixmediaz** [iatenine/Social-Distancing-App#10]
I am kindly requesting for help on how to fix this error

05-11 01:47:55.073 1944-2472/? E/Volley: [167] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:47:55.183 18410-18434/? E/bt_btif: bte_scan_filt_param_cfg_evt, 1
05-11 01:47:58.705 926-2003/? E/Sensors: handleToDriver handle(0)
05-11 01:47:58.718 926-2003/? E/Sensors: new setDelay handle(0),ns(20000000)m, error(0), index(2)
05-11 01:47:59.227 926-1555/? E/Sensors: handleToDriver handle(0)
05-11 01:47:59.240 926-1555/? E/Sensors: new setDelay handle(0),ns(66667000)m, error(0), index(2)
05-11 01:48:00.307 1944-2473/? E/Volley: [168] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:48:04.977 1944-2474/? E/Volley: [169] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:48:05.156 18410-18434/? E/bt_btif: bte_scan_filt_param_cfg_evt, 1
05-11 01:48:10.457 1944-2475/? E/Volley: [170] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:48:15.159 18410-18434/? E/bt_btif: bte_scan_filt_param_cfg_evt, 1
05-11 01:48:15.355 1944-2472/? E/Volley: [167] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:48:20.458 1944-2473/? E/Volley: [168] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report
05-11 01:48:25.158 18410-18434/? E/bt_btif: bte_scan_filt_param_cfg_evt, 1
05-11 01:48:25.298 1944-2474/? E/Volley: [169] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report

I have enabled nearby api and added apikey but still shows  05-11 01:47:55.073 1944-2472/? E/Volley: [167] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/copresence/v2/copresence/report please help

**Comment by iatenine** [comment]
My best guess is this is because the previous commit had an API Key in the manifest that was expired (or the one you added didn't want to play nice). Anyways, I've created a new one and updated the project. Let me know what happens

This project is semi-abandoned due to complications maintaining an API key introduced (and due to it spiraling far beyond the time I truly had available to commit). The pieces should work if you can get Nearby Messages to work properly but is mostly only available if a more experienced Android dev would like to build upon it
